name: git_explorer
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  auto_route: ^10.0.1
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.17
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.2

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Segoe UI
      fonts:
        - asset: fonts/segoe-ui/SegoeUI.ttf
          weight: 400
        - asset: fonts/segoe-ui/SegoeUI_Light.ttf
          weight: 200
        - asset: fonts/segoe-ui/SegoeUI_Semilight.ttf
          weight: 300
        - asset: fonts/segoe-ui/SegoeUI_Semibold.ttf
          weight: 600
        - asset: fonts/segoe-ui/SegoeUI_Bold.ttf
          weight: 700
        - asset: fonts/segoe-ui/SegoeUI_Black.ttf
          weight: 900
