// Mocks generated by Mockito 5.4.5 from annotations
// in git_explorer/test/pages/repo_issues/repository/repo_issues_reposiotry_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i6;
import 'package:git_explorer/pages/repo_issues/api/fetch_repo_issues_api.dart'
    as _i2;
import 'package:git_explorer/pages/repo_issues/models/repo_issue/repo_issue.dart'
    as _i4;
import 'package:git_explorer/pages/repo_issues/models/repo_issue_type/repo_issue_type.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FetchRepoIssuesApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchRepoIssuesApi extends _i1.Mock
    implements _i2.FetchRepoIssuesApi {
  MockFetchRepoIssuesApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.RepoIssue>?> call({
    required String? fullName,
    required int? page,
    int? perPage,
    _i5.IssueStateType? type,
    _i6.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #fullName: fullName,
              #page: page,
              #perPage: perPage,
              #type: type,
              #cancelToken: cancelToken,
            }),
            returnValue: _i3.Future<List<_i4.RepoIssue>?>.value(),
          )
          as _i3.Future<List<_i4.RepoIssue>?>);
}
